---
font: JetBrainsMono Nerd Font 32
background: "#faf4edf0"
color: "#575279"
border: "#907aa9"
border_width: 4
corner_r: 12
padding: 15 # Defaults to corner_r
rows_per_column: 12

# NOTE: Keep launchers shallow: depth <= 2
# NOTE: Nest attributes e.g. music->volume->mute
# NOTE: Keep desc terse, skimmability wins
# NOTE: Keep alpha sorted
# NOTE: Double-tap = the group's default action
# NOTE: Mark non-initial keys like S[l]ack
# NOTE: Submenu by what I am doing
menu:
  - key: " "
    desc: Terminal
    cmd: foot --login tm
  - key: \
    desc: Quick Pass
    cmd: 1password --quick-access

  - key: a
    desc: Audio
    submenu:
      - key: b
        desc: Bitwig Studio
        cmd: bitwig-studio
      - key: c
        desc: Coppwr
        cmd: coppwr
      - key: e
        desc: EasyEffects
        cmd: easyeffects
      - key: m
        desc: Mic
        submenu:
          - key: "0"
            desc: 100%
            cmd: shellctl mic-volume 100
          - key: "3"
            desc: 30%
            cmd: shellctl mic-volume 30
          - key: m
            desc: Mute
            cmd: shellctl mic-mute
      - key: p
        desc: pwvuControl
        cmd: pwvucontrol
      - key: q
        desc: qpwGraph
        cmd: qpwgraph
      - key: t
        desc: Milky[T]racker
        cmd: milkytracker
      - key: y
        desc: Audacit[y]
        cmd: audacity

  - key: b
    desc: Browse
    submenu:
      - key: b
        desc: Firefox
        cmd: firefox
      - key: c
        desc: Copy URL
        cmd: ~/bin/url-from-window
      - key: p
        desc: Private
        cmd: firefox --private-window
      - key: m
        desc: MD URL
        cmd: ~/bin/url-from-window md
      - key: o
        desc: Brave Origin
        cmd: brave-origin
      - key: s
        desc: Search
        cmd: ~/bin/search-fuzzel
      - key: w
        desc: Work Brave
        cmd: brave

  - key: c
    desc: Chats
    submenu:
      - key: d
        desc: Discord
        cmd: discord
      - key: n
        desc: NWW
        cmd: nww
      - key: s
        desc: Signal
        cmd: signal-desktop
      - key: t
        desc: TinTin++
        cmd: foot --app-id=tintin ~/bin/tw

  - key: d
    desc: Shell
    submenu:
      - key: c
        desc: Clipboard
        cmd: shellctl clipboard
      - key: d
        desc: Do Not Disturb
        cmd: shellctl dnd
      - key: i
        desc: Caffeine
        cmd: shellctl caffeine
      - key: n
        desc: Notifications
        cmd: shellctl notifications
      - key: p
        desc: Processes
        cmd: shellctl processlist
      - key: s
        desc: Settings
        cmd: shellctl settings
      - key: w
        desc: Window Rules
        cmd: shellctl window-rules
      - key: x
        desc: Clear Notifs
        cmd: shellctl notifications-clear

  - key: e
    desc: Email
    submenu:
      - key: d
        desc: Dictate Note
        cmd: ~/bin/em-dictate
      - key: e
        desc: Thunderbird
        cmd: thunderbird
      - key: t
        desc: Type Note
        cmd: ~/bin/em-fuzzel

  - key: f
    desc: File Manager
    submenu:
      - key: f
        desc: Yazi
        cmd: foot --app-id=yazi --working-directory=$HOME/Downloads yazi
      - key: n
        desc: Nautilus
        cmd: nautilus
      - key: u
        desc: Upload
        submenu:
        cmd: ~/bin/upload-yazi

  - key: g
    desc: Gaming
    submenu:
      - key: r
        desc: RetroArch
        cmd: retroarch
      - key: s
        desc: Steam
        cmd: steam

  - key: i
    desc: V[i]ewers
    submenu:
      - key: d
        desc: PDF Viewer
        cmd: papers
      - key: i
        desc: Image Viewer
        cmd: loupe
      - key: p
        desc: Image Editor
        cmd: photopea-chromium

  - key: j
    desc: Jump
    submenu:
      - key: b
        desc: Browser
        cmd: ~/bin/focus-app-fuzzel firefox
      - key: e
        desc: Email
        cmd: ~/bin/focus-app-fuzzel thunderbird
      - key: j
        desc: Jump to Win
        cmd: ~/bin/focus-app-fuzzel
      - key: o
        desc: Obsidian
        cmd: ~/bin/focus-app-fuzzel obsidian
      - key: s
        desc: Slack
        cmd: ~/bin/focus-app-fuzzel slack
      - key: t
        desc: Terminal
        cmd: ~/bin/focus-app-fuzzel foot

  - key: "l"
    desc: Back[l]ight
    submenu:
      - key: "1"
        desc: 10%
        cmd: shellctl brightness 10
      - key: "4"
        desc: 40%
        cmd: shellctl brightness 40
      - key: "7"
        desc: 70%
        cmd: shellctl brightness 70

  - key: m
    desc: Music
    submenu:
      - key: " "
        desc: Play/Pause
        cmd: playerctl play-pause
      - key: a
        desc: Amberol
        cmd: amberol
      - key: b
        desc: Prev Track
        cmd: playerctl previous
      - key: m
        desc: Feishin
        cmd: feishin
      - key: n
        desc: Next Track
        cmd: playerctl next
      - key: p
        desc: Picard
        cmd: picard
      - key: v
        desc: Volume
        submenu:
          - key: "0"
            desc: 100%
            cmd: shellctl volume 100
          - key: "3"
            desc: 30%
            cmd: shellctl volume 30
          - key: "6"
            desc: 60%
            cmd: shellctl volume 60
          - key: m
            desc: Mute
            cmd: shellctl mute

  - key: n
    desc: Niri
    submenu:
      - key: c
        desc: Center
        cmd: niri msg action center-column
      - key: e
        desc: Expand
        cmd: niri msg action expand-column-to-available-width
      - key: f
        desc: Float
        cmd: niri msg action toggle-window-floating
      - key: m
        desc: Move Column
        submenu:
          - key: h
            desc: Left
            cmd: niri msg action move-column-to-monitor-left
          - key: j
            desc: Down
            cmd: niri msg action move-column-to-monitor-down
          - key: k
            desc: Up
            cmd: niri msg action move-column-to-monitor-up
          - key: "l"
            desc: Right
            cmd: niri msg action move-column-to-monitor-right
      - key: r
        desc: Reset Height
        cmd: niri msg action reset-window-height
      - key: s
        desc: Swap Focus
        cmd: niri msg action switch-focus-between-floating-and-tiling
      - key: w
        desc: Move Workspace
        submenu:
          - key: h
            desc: Left
            cmd: niri msg action move-workspace-to-monitor-left
          - key: j
            desc: Down
            cmd: niri msg action move-workspace-to-monitor-down
          - key: k
            desc: Up
            cmd: niri msg action move-workspace-to-monitor-up
          - key: "l"
            desc: Right
            cmd: niri msg action move-workspace-to-monitor-right
      - key: z
        desc: Maximi[z]e
        cmd: niri msg action maximize-column

  - key: o
    desc: N[o]tepad
    cmd: xdg-open "obsidian://open?vault=Vault"

  - key: p
    desc: Power
    submenu:
      - key: "l"
        desc: "\U000F033E Lock"
        cmd: shellctl lock
      - key: "p"
        desc: "\U000F0425 Power Off"
        cmd: systemctl poweroff
      - key: "q"
        desc: "\U000F0343 Quit Session"
        cmd: niri msg action quit
      - key: "r"
        desc: "\U000F0465 Reboot"
        cmd: systemctl reboot
      - key: "s"
        desc: "\U000F0904 Suspend"
        cmd: systemctl suspend

  - key: r
    desc: Recording
    submenu:
      - key: b
        desc: Clip Firefox Audio
        cmd: ~/bin/clip_app firefox
      - key: d
        desc: Recor[d] Screen
        cmd: ~/bin/record-screen
      - key: m
        desc: Clip mpv Audio
        cmd: ~/bin/clip_app mpv
      - key: o
        desc: OBS
        cmd: obs
      - key: r
        desc: Screenshot Screen
        cmd: ~/bin/screenshot screen
      - key: s
        desc: Screenshot Selection
        cmd: ~/bin/screenshot selection
      - key: w
        desc: Screenshot Window
        cmd: ~/bin/screenshot window

  - key: s
    desc: Streaming
    submenu:
      - key: b
        desc: VBridger
        cmd: steam steam://rungameid/1898830
      - key: c
        desc: StreamController
        cmd: streamcontroller
      - key: d
        desc: Cast
        submenu:
          - key: c
            desc: Clear
            cmd: niri msg action clear-dynamic-cast-target
          - key: m
            desc: Monitor
            cmd: niri msg action set-dynamic-cast-monitor
          - key: w
            desc: Window
            cmd: niri msg action set-dynamic-cast-window
      - key: f
        desc: Firebot
        cmd: firebot
      - key: o
        desc: OBS
        cmd: obs
      - key: s
        desc: Start Streaming
        cmd: foot ~/bin/streaming_time
      - key: t
        desc: Tuber
        cmd: tuber
      - key: v
        desc: VTube Studio
        cmd: steam steam://rungameid/1325860

  - key: t
    desc: Theme
    submenu:
      - key: d
        desc: Dark/Light
        cmd: shellctl theme-toggle
      - key: g
        desc: Night Light
        cmd: shellctl night-toggle
      - key: n
        desc: Next Wall
        cmd: shellctl wallpaper next
      - key: p
        desc: Prev Wall
        cmd: shellctl wallpaper prev
      - key: r
        desc: Random Wall
        cmd: shellctl wallpaper-random
      - key: s
        desc: Set Wall
        cmd: shellctl wallpaper-browse

  - key: u
    desc: Utilities
    submenu:
      - key: \
        desc: Passwords
        cmd: 1password
      - key: b
        desc: Btop
        cmd: foot --app-id=btop btop
      - key: c
        desc: Calculator
        cmd: gnome-calculator
      - key: d
        desc: Disks
        cmd: gnome-disks
      - key: f
        desc: Font Viewer
        cmd: gnome-font-viewer
      - key: g
        desc: GPU Top
        cmd: foot --app-id=amdgpu_top amdgpu_top
      - key: l
        desc: Co[l]or Picker
        cmd: shellctl color-picker
      - key: p
        desc: " Timer"
        cmd: focus-timer
      - key: t
        desc: Touchpad Toggle
        cmd: ~/bin/toggle-touchpad

  - key: v
    desc: Video
    submenu:
      - key: f
        desc: Filebot
        cmd: filebot
      - key: j
        desc: Jellyfin
        cmd: jellyfin-chromium
      - key: r
        desc: Video T[r]immer
        cmd: video-trimmer
      - key: t
        desc: Twitch
        cmd: twitch-chromium
      - key: v
        desc: Watch url in clipboard
        cmd: ~/bin/watch-url

  - key: w
    desc: Work
    submenu:
      - key: b
        desc: Browser
        cmd: brave
      - key: c
        desc: Cursor
        cmd: cursor
      - key: d
        desc: DNPull
        cmd: foot --working-directory=$HOME/Code --hold ~/bin/dnpull
      - key: e
        desc: Email
        cmd: thunderbird
      - key: n
        desc: Netbird-ui
        cmd: netbird-ui
      - key: o
        desc: Obsidian
        cmd: xdg-open "obsidian://open?vault=DNSimple"
      - key: s
        desc: Slack
        cmd: slack
      - key: t
        desc: " Timer"
        cmd: focus-timer
      - key: v
        desc: VPN
        submenu:
          - key: a
            desc: Amsterdam
            cmd: ~/bin/vpn ams
          - key: h
            desc: Home
            cmd: ~/bin/vpn home
          - key: n
            desc: New York
            cmd: ~/bin/vpn nyc
          - key: s
            desc: San Francisco
            cmd: ~/bin/vpn sfo
      - key: z
        desc: Zoom
        cmd: zoom

  - key: x
    desc: Vo[x]type
    cmd: voxtype record toggle
