#!/usr/bin/env bash

PROFILE_DIR="$HOME/ResilioSync/Documents/machine_profiles"

DROBO_DIR=/Volumes/Drobo/ResilioSync/Documents/machine_profiles
if [[ -d $DROBO_DIR ]]; then
  PROFILE_DIR=$DROBO_DIR
fi

if [[ ! -d "$PROFILE_DIR" ]]; then
  echo "The directory is missing"
  exit 1
fi

/usr/sbin/system_profiler -detailLevel full > "$PROFILE_DIR/$(hostname).txt" 2> /dev/null
