#!/usr/bin/env bash

PACKAGES_DIR="$HOME/.dos_packages"

if [[ ! -d "$PACKAGES_DIR" ]]; then
  echo "packages directory is missing"
  exit 1
fi

echo "This is going to uninstall EVERYTHING and install all my best packages"
echo "Are you super sure?"
read -r _

# shellcheck disable=SC2046
brew remove --force $(brew list) --ignore-dependencies
brew cleanup

while read -r package; do
  brew install "$package"
done < <(cat "$PACKAGES_DIR/standard"/*)

while read -r cask; do
  brew cask install "$cask"
done < <(cat "$PACKAGES_DIR/casks"/*)
