#!/usr/bin/env bash

PACKAGES_DIR="$HOME/.dos_packages"

if [[ ! -d "$PACKAGES_DIR" ]]; then
  echo "packages directory is missing"
  exit 1
fi

##
# Doing an upgrade first prevents errors
brew upgrade

cat "$PACKAGES_DIR/standard"/* | xargs brew install

##
# cask is weird so re-install just in case
cat "$PACKAGES_DIR/casks"/* | xargs brew cask reinstall
