[mgr]
prepend_keymap = [
  # drag from Yazi
  { on = "<C-d>", run = "shell -- ripdrag %s --all" },

  # quickshell
  { on = "!", run = 'shell "$SHELL" --block', desc = "Open $SHELL in CWD" },

  # fastjump
  { on = "f", run = "plugin jump-to-char", desc = "Jump to char" },

  # tabs
  { on = "<C-n>", run = "tab_switch --relative 1", desc = "Switch to next tab" },
  { on = "<C-p>", run = "tab_switch --relative -1", desc = "Switch to previous tab" },
  { on = ["t", "c"], run = "close", desc = "Close current tab" },

  # bookmarks jump
  { on = ["g", "b"], run = "back", desc = "Go back" },
  { on = ["g", "c"], run = "cd ~/Code", desc = "Go Code" },
  { on = ["g", "e"], run = "cd sftp://edelgard//deep_end", desc = "Go Edelgard" },
  { on = ["g", "i"], run = "cd ~/Sync/Inbox", desc = "Go Inbox" },
  { on = ["g", "m"], run = "plugin gvfs -- jump-to-device", desc = "Select device to mount & jump to" },
  { on = ["g", "n"], run = "cd ~/Code/nixos-skwrls", desc = "Go Nix" },
  { on = ["g", "o"], run = "cd ~/.homesick/repos/dotfiles", desc = "Go Dotfiles" },
  { on = ["g", "p"], run = "cd sftp://piper", desc = "Go Piper" },
  { on = ["g", "t"], run = "plugin recycle-bin -- open", desc = "Go Trash" },

  # add fzf and zoxide
  { on = ["g", "z"], run = "plugin zoxide", desc = "Jump via zoxide" },
  { on = ["g", "Z"], run = "plugin fzf", desc = "Jump via fzf" },

  # trash
  { on = ["T", "o"], run = "plugin recycle-bin -- open", desc = "Open Trash" },
  { on = ["T", "e"], run = "plugin recycle-bin -- empty", desc = "Empty Trash" },
  { on = ["T", "d"], run = "plugin recycle-bin -- emptyDays", desc = "Empty by days deleted" },
  { on = ["T", "r"], run = "plugin recycle-bin -- restore", desc = "Restore from Trash" },

  # mount
  { on = ["M", "m"], run = "plugin gvfs -- select-then-mount --jump", desc = "Select device to mount & jump to" },
  { on = ["M", "u"], run = "plugin gvfs -- select-then-unmount --eject", desc = "Select device then eject" },

  { on = ["M", "a"], run = "plugin gvfs -- add-mount", desc = "Add a GVFS mount URI" },
  { on = ["M", "e"], run = "plugin gvfs -- edit-mount", desc = "Edit a GVFS mount URI" },
  { on = ["M", "r"], run = "plugin gvfs -- remove-mount", desc = "Remove a GVFS mount URI" },
]
