[mgr]
sort_by = "mtime"
sort_reverse = true
sort_dir_first = true

[[opener.set-wallpaper]]
run = "wall set %s1"
for = "linux"
desc = "Set as wallpaper"

[[opener.upload-zipline]]
run = "upload %s"
for = "linux"
desc = "Upload to zipline"

[open]
prepend_rules = [
  { mime = "image/**", use = ["open", "set-wallpaper", "upload-zipline", "reveal"] },
]

[plugin]
prepend_fetchers = [
  # ftp.yazi: custom schemes aren't matched by remote://, route mime manually
  { url = "ftp://*", run = "mime.remote", prio = "high", group = "mime" },
]
prepend_preloaders = [
  # Do not preload files in mounted locations:
  { url = "/run/user/1000/gvfs/**/*", run = "noop" },
  { url = "/run/media/dos/**/*", run = "noop" },
]
