# Bar layout + widget tuning

[bar.default]
start = ["taskbar", "tray"]
center = ["media"]
end = ["privacy", "group:g4", "group:g5", "group:g3", "group:g1"]
font_weight = 700
margin_ends = 30
margin_opposit420 = 1
background_opacity = 0.67
radius = 15

[[bar.default.capsule_group]]
accordion = false
accordion_direction = "end"
enabled = true
fill = "surface_variant"
id = "g3"
members = ["network", "bluetooth", "vpn"]
opacity = 1.0
padding = 3.0
widget_spacing = 0

[[bar.default.capsule_group]]
accordion = false
accordion_direction = "end"
enabled = true
fill = "surface_variant"
id = "g4"
members = ["status", "recorder"]
opacity = 1.0
padding = 3.0
widget_spacing = 1

[[bar.default.capsule_group]]
accordion = false
accordion_direction = "end"
enabled = true
fill = "surface_variant"
id = "g5"
members = ["caffeine", "power_profile", "battery"]
opacity = 1.0
padding = 3.0
widget_spacing = 2

[[bar.default.capsule_group]]
accordion = false
accordion_direction = "end"
enabled = true
fill = "surface_variant"
id = "g1"
members = ["bar", "clock"]
opacity = 1.0
padding = 5.0
widget_spacing = 4

[widget.bar]
type = "noctalia/world_clock:bar"

[widget.clock]
format = "{:%a %b %e, %H:%M}"

[widget.media]
capsule = true
max_length = 420

[widget.network]
show_label = false
vpn_status = "both"

[widget.privacy]
capsule = true

[widget.recorder]
type = "noctalia/screen_recorder:recorder"

[widget.status]
type = "gabedunn/voxtype:status"

[widget.taskbar]
group_by_workspace = true
hide_empty_workspaces = true

[widget.tray]
capsule = true

[widget.vpn]
type = "dos/vpn:status"
