[idle]
behavior_order = ["idle-behavior", "lock", "screen-off", "lock-and-suspend"]

[idle.behavior.idle-behavior]
action = "command"
command = "notify-send \"Locking in one minute\""
enabled = true
resume_command = "notify-send \"Oh, nvrmd. Welcome back.\""
timeout = 240.0

[idle.behavior.lock]
action = "lock"
enabled = true
timeout = 300.0

[idle.behavior.lock-and-suspend]
action = "lock_and_suspend"
enabled = true
timeout = 600.0

[idle.behavior.screen-off]
action = "screen_off"
enabled = true
timeout = 360.0
