font=RecMonoDuotone Nerd Font Propo:size=26
use-bold=true

enable-mouse=false
icons-enabled=yes
terminal=foot {cmd}

# Gruvbox Dark medium (see docs/gruvbox.md)
[colors]
background=282828ee
text=ebdbb2ff
prompt=ebdbb2ff
placeholder=928374ff
input=ebdbb2ff
match=fabd2fff
selection=665c54ee
selection-text=ebdbb2ff
selection-match=fabd2fff
counter=fe8019ff
border=fabd2fff

[border]
width=2
radius=20
selection-radius=16
