font=RecMonoDuotone Nerd Font Propo:size=26
use-bold=true

enable-mouse=false
icons-enabled=yes
terminal=foot {cmd}

# Everforest Light Hard (see docs/everforest.md)
[colors]
background=fffbefee
text=5c6a72ff
prompt=5c6a72ff
placeholder=a6b0a0ff
input=5c6a72ff
match=8da101ff
selection=f0f2d4ee
selection-text=5c6a72ff
selection-match=8da101ff
counter=dfa000ff
border=8da101ff

[border]
width=4
radius=20
selection-radius=16
