font=RecMonoDuotone Nerd Font Propo:size=26
use-bold=true

enable-mouse=false
icons-enabled=yes
terminal=foot {cmd}

# RosePine Dawn
# https://github.com/bomgar/rose-pine-fuzzel
[colors]
background=faf4eddd
text=575279ff
prompt=575279dd
placeholder=9893a5dd
input=575279ff
match=d7827eff
selection=dfdad9dd
selection-text=575279ff
selection-match=d7827eff
counter=ea9d34dd
border=d7827edd

[border]
width=4
radius=20
selection-radius=16
