#!/usr/bin/env bash
# shellcheck disable=SC2059
# shellcheck disable=SC2086

if [[ ! -e metadata.rb ]]; then
  # Not a chef
  exit 0
fi

RED='\033[0;31m'
GREEN='\033[0;32m'
NO_COLOR='\033[0m'
CLEAR_LINE='\r\033[K'

suspects="$(comm -12 <(git diff --cached --name-only --diff-filter=AMC | sort) <(rubocop --list-target-files 2> /dev/null | sort) | tr '\n' ' ')"

printf "${CLEAR_LINE}🚔   Linting files: ${suspects}\n"
if ! chef exec cookstyle --format simple ${suspects} #> /dev/null
then
  printf "${CLEAR_LINE}${RED}💀   Rubocop found some issues. Fix, stage, and commit again${NO_COLOR}\n"
  printf "ℹ️   Try 'chef exec cookstyle aA; and git add -p'\n"
  exit -1
fi

if ! chef exec foodcritic . #> /dev/null
then
  printf "${CLEAR_LINE}${RED}💀   foodcritic found some issues. Fix, stage, and commit again${NO_COLOR}\n"
  exit -1
fi

printf "${CLEAR_LINE}🎊${GREEN}   Rubocop foodcritic are appeased.${NO_COLOR}\n"
exit 0
