# Yay

tap 'homebrew/services'

## Upgrades & Overlays

brew 'bat'
brew 'btop'
brew 'curl'
brew 'eza'
brew 'fd'
brew 'fish'
brew 'fzf'
brew 'gawk'
brew 'httpie'
brew 'mosh'
brew 'openssh'
brew 'ripgrep'
brew 'rsync'
brew 'sevenzip' #yazi
brew 'tmux'
brew 'watch'
brew 'wget'
brew 'yazi'
brew 'zoxide'

## Fun stuff

brew 'fastfetch'
brew 'ffmpeg'
brew 'hugo'
brew 'imagemagick'
brew 'marp-cli' # slides
brew 'media-info'
brew 'msmtp'
brew 'ncdu'
brew 'poppler' # pdf tools
brew 'qpdf' # moar pdf
brew 'streamlink'
brew 'syncthing'
brew 'tintin'
brew 'tlrc'
brew 'trash-cli'
brew 'yt-dlp'

## Dev Tooling

brew 'ast-grep'
brew 'gnu-sed' # neovim Spectre needs this
brew 'cmake' # neovim build needs
brew 'direnv'
brew 'entr'
brew 'gh'
brew 'git'
brew 'git-lfs'
brew 'git-standup'
brew 'git-xargs'
brew 'go'
brew 'golangci-lint'
brew 'luarocks'
brew 'jq'
brew 'just'
brew 'libpq'
brew 'neovim'
brew 'overmind'
brew 'pipx'

tap 'goreleaser/tap'
brew 'goreleaser/tap/goreleaser'

tap 'jesseduffield/lazygit'
brew 'jesseduffield/lazygit/lazygit'

## Ops Tooling

brew 'csvlens'
brew 'dive'
brew 'gnupg'
brew 'gping'
brew 'miller'
brew 'nmap'
brew 'qrencode'
brew 'whois'
brew 'wireguard-tools'

tap '1password/tap'
cask '1password/tap/1password-cli'

tap 'hashicorp/tap'
brew 'hashicorp/tap/terraform'

tap 'jesseduffield/lazydocker'
brew 'jesseduffield/lazydocker/lazydocker'

## MAS time

brew 'mas'
