brew "asdf"
brew "bat"
brew "bat-extras"
brew "btop"
brew "claude-squad"
brew "cmake"
brew "csvlens"
brew "curl"
brew "delve"
brew "direnv"
brew "dive"
brew "entr"
brew "entr" # File watcher for automation
brew "eslint"
brew "eza"
brew "fastfetch"
brew "fd"
brew "ffmpeg"
brew "fish"
brew "fx" # json browser
brew "fzf"
brew "gawk"
brew "gh"
brew "git"
brew "git-delta"
brew "git-lfs"
brew "git-standup"
brew "git-xargs"
brew "gnupg"
brew "go"
brew "golangci-lint"
brew "gopls"
brew "goreleaser"
brew "hugo"
brew "imagemagick"
brew "jq" # json parser
brew "just"
brew "lazygit"
brew "libpq"
brew "marp-cli"
brew "mas"
brew "media-info"
brew "miller" # awk++ for structured data
brew "mosh"
brew "msmtp"
brew "ncdu"
brew "nmap"
brew "openssh"
brew "overmind"
brew "poppler"
brew "prettier"
brew "python3"
brew "qpdf"
brew "qrencode"
brew "restic"
brew "ripgrep"
brew "rsync"
brew "ruff"
brew "sevenzip"
brew "syncthing", restart_service: :changed
brew "tea"
brew "tf-summarize"
brew "tintin"
brew "tlrc"
brew "tmux"
brew "ty"
brew "typescript"
brew "typescript-language-server"
brew "uv"
brew "vtsls"
brew "watch"
brew "wget"
brew "whois"
brew "wireguard-tools"
brew "xh" # httpie replacement
brew "yazi"
brew "yq" # yaml parser
brew "yt-dlp"
brew "zoxide"

# NeoVim mass
brew "neovim"

brew "ast-grep" # grug-far
brew "chafa" # fzf-lua
brew "node@24"
brew "tree-sitter"
brew "tree-sitter-cli"
brew "viu" # fzf-lua

# lua
brew "lua-language-server"
brew "lua"
brew "luarocks"
brew "stylua"

# markdown
brew "markdownlint-cli2"
brew "marksman"

# configuration
# brew "fixjson"
brew "tombi"
brew "vacuum"
brew "vscode-langservers-extracted" # json, html, css
brew "yaml-language-server"
brew "yamlfmt"
brew "yamllint"

# shells
brew "bash-language-server"
brew "fish-lsp"
brew "shellcheck"
brew "shfmt"

# docker
brew "docker-compose-langserver"
brew "docker-language-server"
brew "hadolint"

tap "hashicorp/tap"
brew "hashicorp/tap/terraform"

tap "jesseduffield/lazydocker"
brew "jesseduffield/lazydocker/lazydocker"

cask "1password-cli"
cask "espanso"

go "github.com/StackExchange/dnscontrol/v4"

cargo "bandsnatch"
cargo "sqlx-cli"
