brew "asdf"
brew "bat"
brew "bat-extras"
brew "btop"
brew "cmake"
brew "csvlens"
brew "curl"
brew "direnv"
brew "dive"
brew "dua-cli"
brew "duf"
brew "entr" # File watcher for automation
brew "eza"
brew "fastfetch"
brew "fd"
brew "ffmpeg"
brew "fish"
brew "fx" # json browser
brew "fzf"
brew "gawk"
brew "gh"
brew "git"
brew "git-delta"
brew "git-lfs"
brew "git-standup"
brew "gnupg"
brew "herdr"
brew "hugo"
brew "imagemagick"
brew "jq" # json parser
brew "jujutsu"
brew "just"
brew "lazygit"
brew "marp-cli"
brew "mas"
brew "media-info"
brew "miller" # awk++ for structured data
brew "mosh"
brew "msmtp"
brew "ncdu"
brew "nmap"
brew "openssh"
brew "overmind"
brew "python3"
brew "qpdf"
brew "qrencode"
brew "restic"
brew "ripgrep"
brew "rsync"
brew "syncthing", restart_service: :changed
brew "tea"
brew "tintin"
brew "tlrc"
brew "tmux"
brew "trash-cli"
brew "tuicr"
brew "watch"
brew "wget"
brew "whois"
brew "wireguard-tools"
brew "xh" # httpie replacement
brew "yq" # yaml parser
brew "yt-dlp"
brew "zoxide"

# yazi
brew "yazi"
brew "poppler"
brew "sevenzip"

# NeoVim mass
brew "neovim"

brew "ast-grep" # grug-far
brew "chafa" # fzf-lua
brew "node@24"
brew "tree-sitter"
brew "tree-sitter-cli"
brew "viu" # fzf-lua

# lua
brew "lua-language-server"
brew "lua"
brew "luarocks"
brew "stylua"

# markdown
brew "markdownlint-cli2"
brew "marksman"

# configuration
brew "prettier"
brew "tombi"
brew "vacuum"
brew "vscode-langservers-extracted" # json, html, css
brew "yaml-language-server"
brew "yamlfmt"
brew "yamllint"

# java(script)
brew "typescript"
brew "typescript-language-server"
brew "vtsls"
brew "eslint"

# shells
brew "bash-language-server"
brew "fish-lsp"
brew "shellcheck"
brew "shfmt"

# docker
brew "docker-compose-langserver"
brew "docker-language-server"
brew "hadolint"

# golang
brew "go"
brew "golangci-lint"
brew "gopls"
brew "goreleaser"

# python
brew "ty"
brew "uv"
brew "ruff"

cask "1password-cli"
cask "espanso"

go "github.com/StackExchange/dnscontrol/v4"
